### ISSUE TITLE
Don't push Docker image during PR's CI

### ISSUE THREAD

**Issue by ddundo** [mesh-adaptation/mesh-adaptation-docs#55]
I think we should have two separate steps in `reusable_docker_build.yml`:

```
      - name: 'Build Docker Container'
        id: build
        if: ${{ steps.changed-files.outputs.any_changed == 'true' }}
        uses: docker/build-push-action@v5
        with:
          push: false
          no-cache: true
          file: ${{ inputs.dockerfile-path }}
          tags: temp-tag

      - name: 'Build and Push Docker Container to GitHub Container Registry'
        id: build-and-push
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/build-push-action@v5
        with:
          push: true
          no-cache: true
          file: ${{ inputs.dockerfile-path }}
          tags: ${{ inputs.docker-image-tag }}
```

where the first one will be run during PRs to check that the build succeeds, but will not push to ghcr.io. The image will be pushed only if the workflow is called from the main branch (i.e. during schedule events or merged PRs).

Do you agree @jwallwork23? I will do this if you do
